services:

  dwarf-gateway:
    build:
      context: .
      dockerfile: ./dockerfile.gateway
    expose: 
      - 8080
    ports:
      - "8080:8080"

  dwarf-upstream:
    build: 
      context: .
      dockerfile: ./dockerfile.upstream
    links:
      - dwarf-gateway
    environment: 
      - GATEWAY_HOST=dwarf-gateway
      - GATEWAY_PORT=8080
    expose: 
      - 8082
    ports:
      - "8082:8082"

  dwarf-monitor:
    build: 
      context: .
      dockerfile: ./dockerfile.monitor
    links:
      - dwarf-gateway
    environment: 
      - GATEWAY_HOST=dwarf-gateway
      - GATEWAY_PORT=8080
    expose: 
      - 8081
    ports:
      - "8081:8081"

  dwarf-demo-typescript:
    build: 
      context: .
      dockerfile: ./dockerfile.demo-typescript
    links:
      - dwarf-gateway
    environment: 
      - GATEWAY_HOST=dwarf-gateway
      - GATEWAY_PORT=8080

  dwarf-demo-nodejs:
    build: 
      context: .
      dockerfile: ./dockerfile.demo-nodejs
    links:
      - dwarf-gateway
    environment: 
      - GATEWAY_HOST=dwarf-gateway
      - GATEWAY_PORT=8080