services:

  gateway:
    build:
      context: .
      dockerfile: packages/gateway/Dockerfile
    expose: 
      - 38080
    ports:
      - "38080:38080"
    environment: 
      - PORT=38080
      - BROKER_TYPE=local

  upstream:
    build: 
      context: .
      dockerfile: packages/upstream/Dockerfile
    links:
      - gateway
    environment: 
      - GATEWAY_HOST=gateway
      - GATEWAY_PORT=38080
    expose: 
      - 8082
    ports:
      - "38082:38082"

  monitor:
    build: 
      context: .
      dockerfile: packages/monitor/Dockerfile
    links:
      - gateway
    environment: 
      - GATEWAY_HOST=gateway
      - GATEWAY_PORT=38080
    expose: 
      - 8081
    ports:
      - "38081:38081"

  demo-typescript:
    build: 
      context: .
      dockerfile: packages/demo-typescript/Dockerfile
    links:
      - gateway
    environment: 
      - GATEWAY_HOST=gateway
      - GATEWAY_PORT=38080

  demo-nodejs:
    build: 
      context: .
      dockerfile: packages/demo-nodejs/Dockerfile
    links:
      - gateway
    environment: 
      - GATEWAY_HOST=gateway
      - GATEWAY_PORT=38080